# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.ledger_account_opening_balance import LedgerAccountOpeningBalance  # noqa: E501
from sage.rest import ApiException

class TestLedgerAccountOpeningBalance(unittest.TestCase):
    """LedgerAccountOpeningBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LedgerAccountOpeningBalance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.ledger_account_opening_balance.LedgerAccountOpeningBalance()  # noqa: E501
        if include_optional :
            return LedgerAccountOpeningBalance(
                id = '0', 
                displayed_as = '0', 
                path = '0', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                ledger_account = sage.models.base.Base(
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                details = '0', 
                debit = 1.337, 
                credit = 1.337
            )
        else :
            return LedgerAccountOpeningBalance(
        )

    def testLedgerAccountOpeningBalance(self):
        """Test LedgerAccountOpeningBalance"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
