# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.bank_deposits_api import BankDepositsApi  # noqa: E501
from sage.rest import ApiException


class TestBankDepositsApi(unittest.TestCase):
    """BankDepositsApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.bank_deposits_api.BankDepositsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_bank_deposits_key(self):
        """Test case for delete_bank_deposits_key

        Deletes a Bank Deposit  # noqa: E501
        """
        pass

    def test_get_bank_deposits(self):
        """Test case for get_bank_deposits

        Returns all Bank Deposits  # noqa: E501
        """
        pass

    def test_get_bank_deposits_key(self):
        """Test case for get_bank_deposits_key

        Returns a Bank Deposit  # noqa: E501
        """
        pass

    def test_post_bank_deposits(self):
        """Test case for post_bank_deposits

        Creates a Bank Deposit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
