# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.tax_return_frequencies_api import TaxReturnFrequenciesApi  # noqa: E501
from sage.rest import ApiException


class TestTaxReturnFrequenciesApi(unittest.TestCase):
    """TaxReturnFrequenciesApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.tax_return_frequencies_api.TaxReturnFrequenciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tax_return_frequencies(self):
        """Test case for get_tax_return_frequencies

        Returns all Tax Return Frequencies  # noqa: E501
        """
        pass

    def test_get_tax_return_frequencies_key(self):
        """Test case for get_tax_return_frequencies_key

        Returns a Tax Return Frequency  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
