# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.live_exchange_rate import LiveExchangeRate  # noqa: E501
from sage.rest import ApiException

class TestLiveExchangeRate(unittest.TestCase):
    """LiveExchangeRate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LiveExchangeRate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.live_exchange_rate.LiveExchangeRate()  # noqa: E501
        if include_optional :
            return LiveExchangeRate(
                displayed_as = '0', 
                path = '0', 
                rate = 1.337, 
                inverse_rate = 1.337, 
                base_currency = sage.models.base.Base(
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                currency = sage.models.base.Base(
                    id = '0', 
                    displayed_as = '0', 
                    __path = '0', ), 
                retrieved_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return LiveExchangeRate(
        )

    def testLiveExchangeRate(self):
        """Test LiveExchangeRate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
