# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.post_bank_accounts_bank_account_bank_account_details import PostBankAccountsBankAccountBankAccountDetails  # noqa: E501
from sage.rest import ApiException

class TestPostBankAccountsBankAccountBankAccountDetails(unittest.TestCase):
    """PostBankAccountsBankAccountBankAccountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostBankAccountsBankAccountBankAccountDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.post_bank_accounts_bank_account_bank_account_details.PostBankAccountsBankAccountBankAccountDetails()  # noqa: E501
        if include_optional :
            return PostBankAccountsBankAccountBankAccountDetails(
                account_name = '0', 
                account_number = '0', 
                sort_code = '0', 
                bic = '0', 
                iban = '0'
            )
        else :
            return PostBankAccountsBankAccountBankAccountDetails(
                account_name = '0',
        )

    def testPostBankAccountsBankAccountBankAccountDetails(self):
        """Test PostBankAccountsBankAccountBankAccountDetails"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
