# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.service_rate_types_api import ServiceRateTypesApi  # noqa: E501
from sage.rest import ApiException


class TestServiceRateTypesApi(unittest.TestCase):
    """ServiceRateTypesApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.service_rate_types_api.ServiceRateTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_service_rate_types_key(self):
        """Test case for delete_service_rate_types_key

        Deletes a Service Rate Type  # noqa: E501
        """
        pass

    def test_get_service_rate_types(self):
        """Test case for get_service_rate_types

        Returns all Service Rate Types  # noqa: E501
        """
        pass

    def test_get_service_rate_types_key(self):
        """Test case for get_service_rate_types_key

        Returns a Service Rate Type  # noqa: E501
        """
        pass

    def test_post_service_rate_types(self):
        """Test case for post_service_rate_types

        Creates a Service Rate Type  # noqa: E501
        """
        pass

    def test_put_service_rate_types_key(self):
        """Test case for put_service_rate_types_key

        Updates a Service Rate Type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
