# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.post_attachments import PostAttachments  # noqa: E501
from sage.rest import ApiException

class TestPostAttachments(unittest.TestCase):
    """PostAttachments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostAttachments
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.post_attachments.PostAttachments()  # noqa: E501
        if include_optional :
            return PostAttachments(
                attachment = sage.models.post_attachments_attachment.postAttachments_attachment(
                    file = '0', 
                    file_name = '0', 
                    mime_type = '0', 
                    description = '0', 
                    file_extension = '0', 
                    transaction_id = '0', 
                    file_size = 0, 
                    attachment_context_type_id = '0', 
                    attachment_context_id = '0', 
                    is_public = True, )
            )
        else :
            return PostAttachments(
                attachment = sage.models.post_attachments_attachment.postAttachments_attachment(
                    file = '0', 
                    file_name = '0', 
                    mime_type = '0', 
                    description = '0', 
                    file_extension = '0', 
                    transaction_id = '0', 
                    file_size = 0, 
                    attachment_context_type_id = '0', 
                    attachment_context_id = '0', 
                    is_public = True, ),
        )

    def testPostAttachments(self):
        """Test PostAttachments"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
