# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.contact_cis_deduction_rate import ContactCisDeductionRate  # noqa: E501
from sage.rest import ApiException

class TestContactCisDeductionRate(unittest.TestCase):
    """ContactCisDeductionRate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ContactCisDeductionRate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.contact_cis_deduction_rate.ContactCisDeductionRate()  # noqa: E501
        if include_optional :
            return ContactCisDeductionRate(
                id = '0', 
                displayed_as = '0', 
                path = '0'
            )
        else :
            return ContactCisDeductionRate(
        )

    def testContactCisDeductionRate(self):
        """Test ContactCisDeductionRate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
