# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.post_journals_journal_journal_code import PostJournalsJournalJournalCode  # noqa: E501
from sage.rest import ApiException

class TestPostJournalsJournalJournalCode(unittest.TestCase):
    """PostJournalsJournalJournalCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostJournalsJournalJournalCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.post_journals_journal_journal_code.PostJournalsJournalJournalCode()  # noqa: E501
        if include_optional :
            return PostJournalsJournalJournalCode(
                name = '0', 
                code = '0', 
                journal_code_type_id = '0', 
                control_name = '0', 
                reserved = True
            )
        else :
            return PostJournalsJournalJournalCode(
        )

    def testPostJournalsJournalJournalCode(self):
        """Test PostJournalsJournalJournalCode"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
