# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.put_bank_transfers import PutBankTransfers  # noqa: E501
from sage.rest import ApiException

class TestPutBankTransfers(unittest.TestCase):
    """PutBankTransfers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PutBankTransfers
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.put_bank_transfers.PutBankTransfers()  # noqa: E501
        if include_optional :
            return PutBankTransfers(
                bank_transfer = sage.models.put_bank_transfers_bank_transfer.putBankTransfers_bank_transfer(
                    from_bank_account_id = '0', 
                    to_bank_account_id = '0', 
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    amount = 1.337, 
                    reference = '0', 
                    description = '0', )
            )
        else :
            return PutBankTransfers(
                bank_transfer = sage.models.put_bank_transfers_bank_transfer.putBankTransfers_bank_transfer(
                    from_bank_account_id = '0', 
                    to_bank_account_id = '0', 
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    amount = 1.337, 
                    reference = '0', 
                    description = '0', ),
        )

    def testPutBankTransfers(self):
        """Test PutBankTransfers"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
