# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.put_bank_opening_balances_bank_opening_balance import PutBankOpeningBalancesBankOpeningBalance  # noqa: E501
from sage.rest import ApiException

class TestPutBankOpeningBalancesBankOpeningBalance(unittest.TestCase):
    """PutBankOpeningBalancesBankOpeningBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PutBankOpeningBalancesBankOpeningBalance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.put_bank_opening_balances_bank_opening_balance.PutBankOpeningBalancesBankOpeningBalance()  # noqa: E501
        if include_optional :
            return PutBankOpeningBalancesBankOpeningBalance(
                bank_account_id = '0', 
                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                debit = 1.337, 
                credit = 1.337, 
                transaction_type_id = '0'
            )
        else :
            return PutBankOpeningBalancesBankOpeningBalance(
        )

    def testPutBankOpeningBalancesBankOpeningBalance(self):
        """Test PutBankOpeningBalancesBankOpeningBalance"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
