# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.address_regions_api import AddressRegionsApi  # noqa: E501
from sage.rest import ApiException


class TestAddressRegionsApi(unittest.TestCase):
    """AddressRegionsApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.address_regions_api.AddressRegionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_address_regions(self):
        """Test case for get_address_regions

        Returns all Address Regions  # noqa: E501
        """
        pass

    def test_get_address_regions_key(self):
        """Test case for get_address_regions_key

        Returns a Address Region  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
