# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.contact_person_types_api import ContactPersonTypesApi  # noqa: E501
from sage.rest import ApiException


class TestContactPersonTypesApi(unittest.TestCase):
    """ContactPersonTypesApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.contact_person_types_api.ContactPersonTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contact_person_types(self):
        """Test case for get_contact_person_types

        Returns all Contact Person Types  # noqa: E501
        """
        pass

    def test_get_contact_person_types_key(self):
        """Test case for get_contact_person_types_key

        Returns a Contact Person Type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
