# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.contact_opening_balances_api import ContactOpeningBalancesApi  # noqa: E501
from sage.rest import ApiException


class TestContactOpeningBalancesApi(unittest.TestCase):
    """ContactOpeningBalancesApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.contact_opening_balances_api.ContactOpeningBalancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_contact_opening_balances_key(self):
        """Test case for delete_contact_opening_balances_key

        Deletes a Contact Opening Balance  # noqa: E501
        """
        pass

    def test_get_contact_opening_balances(self):
        """Test case for get_contact_opening_balances

        Returns all Contact Opening Balances  # noqa: E501
        """
        pass

    def test_get_contact_opening_balances_key(self):
        """Test case for get_contact_opening_balances_key

        Returns a Contact Opening Balance  # noqa: E501
        """
        pass

    def test_post_contact_opening_balances(self):
        """Test case for post_contact_opening_balances

        Creates a Contact Opening Balance  # noqa: E501
        """
        pass

    def test_put_contact_opening_balances_key(self):
        """Test case for put_contact_opening_balances_key

        Updates a Contact Opening Balance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
