# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.purchase_corrective_invoices_api import PurchaseCorrectiveInvoicesApi  # noqa: E501
from sage.rest import ApiException


class TestPurchaseCorrectiveInvoicesApi(unittest.TestCase):
    """PurchaseCorrectiveInvoicesApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.purchase_corrective_invoices_api.PurchaseCorrectiveInvoicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_purchase_corrective_invoices_key(self):
        """Test case for delete_purchase_corrective_invoices_key

        Deletes a Purchase Corrective Invoice  # noqa: E501
        """
        pass

    def test_get_purchase_corrective_invoices(self):
        """Test case for get_purchase_corrective_invoices

        Returns all Purchase Corrective Invoices  # noqa: E501
        """
        pass

    def test_get_purchase_corrective_invoices_key(self):
        """Test case for get_purchase_corrective_invoices_key

        Returns a Purchase Corrective Invoice  # noqa: E501
        """
        pass

    def test_post_purchase_corrective_invoices(self):
        """Test case for post_purchase_corrective_invoices

        Creates a Purchase Corrective Invoice  # noqa: E501
        """
        pass

    def test_put_purchase_corrective_invoices_key(self):
        """Test case for put_purchase_corrective_invoices_key

        Updates a Purchase Corrective Invoice  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
