# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sage
from sage.api.coa_accounts_api import CoaAccountsApi  # noqa: E501
from sage.rest import ApiException


class TestCoaAccountsApi(unittest.TestCase):
    """CoaAccountsApi unit test stubs"""

    def setUp(self):
        self.api = sage.api.coa_accounts_api.CoaAccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_coa_accounts(self):
        """Test case for get_coa_accounts

        Returns all Coa Accounts  # noqa: E501
        """
        pass

    def test_get_coa_accounts_key(self):
        """Test case for get_coa_accounts_key

        Returns a Coa Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
