# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sage
from sage.models.ledger_account_balance_details import LedgerAccountBalanceDetails  # noqa: E501
from sage.rest import ApiException

class TestLedgerAccountBalanceDetails(unittest.TestCase):
    """LedgerAccountBalanceDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LedgerAccountBalanceDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sage.models.ledger_account_balance_details.LedgerAccountBalanceDetails()  # noqa: E501
        if include_optional :
            return LedgerAccountBalanceDetails(
                balance = 1.337, 
                credit_or_debit = '0', 
                credits = 1.337, 
                debits = 1.337, 
                from_date = '0', 
                to_date = '0'
            )
        else :
            return LedgerAccountBalanceDetails(
        )

    def testLedgerAccountBalanceDetails(self):
        """Test LedgerAccountBalanceDetails"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
