# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sage.configuration import Configuration


class PostHostedArtefactPaymentSettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hosted_artefact_payment_setting': 'PostHostedArtefactPaymentSettingsHostedArtefactPaymentSetting'
    }

    attribute_map = {
        'hosted_artefact_payment_setting': 'hosted_artefact_payment_setting'
    }

    def __init__(self, hosted_artefact_payment_setting=None, local_vars_configuration=None):  # noqa: E501
        """PostHostedArtefactPaymentSettings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._hosted_artefact_payment_setting = None
        self.discriminator = None

        self.hosted_artefact_payment_setting = hosted_artefact_payment_setting

    @property
    def hosted_artefact_payment_setting(self):
        """Gets the hosted_artefact_payment_setting of this PostHostedArtefactPaymentSettings.  # noqa: E501


        :return: The hosted_artefact_payment_setting of this PostHostedArtefactPaymentSettings.  # noqa: E501
        :rtype: PostHostedArtefactPaymentSettingsHostedArtefactPaymentSetting
        """
        return self._hosted_artefact_payment_setting

    @hosted_artefact_payment_setting.setter
    def hosted_artefact_payment_setting(self, hosted_artefact_payment_setting):
        """Sets the hosted_artefact_payment_setting of this PostHostedArtefactPaymentSettings.


        :param hosted_artefact_payment_setting: The hosted_artefact_payment_setting of this PostHostedArtefactPaymentSettings.  # noqa: E501
        :type: PostHostedArtefactPaymentSettingsHostedArtefactPaymentSetting
        """
        if self.local_vars_configuration.client_side_validation and hosted_artefact_payment_setting is None:  # noqa: E501
            raise ValueError("Invalid value for `hosted_artefact_payment_setting`, must not be `None`")  # noqa: E501

        self._hosted_artefact_payment_setting = hosted_artefact_payment_setting

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostHostedArtefactPaymentSettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PostHostedArtefactPaymentSettings):
            return True

        return self.to_dict() != other.to_dict()
