# coding: utf-8

"""
    Sage Business Cloud Accounting - Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sage.configuration import Configuration


class PutContactPaymentsContactPayment(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'transaction_type_id': 'str',
        'contact_id': 'str',
        'bank_account_id': 'str',
        'date': 'date',
        'total_amount': 'float',
        'payment_method_id': 'str',
        'net_amount': 'float',
        'tax_amount': 'float',
        'currency_id': 'str',
        'exchange_rate': 'float',
        'base_currency_net_amount': 'float',
        'base_currency_tax_amount': 'float',
        'base_currency_total_amount': 'float',
        'base_currency_currency_charge': 'float',
        'reference': 'str',
        'tax_rate_id': 'str',
        'allocated_artefacts': 'list[PostContactPaymentsContactPaymentAllocatedArtefacts]',
        'payment_on_account': 'PostContactPaymentsContactPaymentPaymentOnAccount'
    }

    attribute_map = {
        'transaction_type_id': 'transaction_type_id',
        'contact_id': 'contact_id',
        'bank_account_id': 'bank_account_id',
        'date': 'date',
        'total_amount': 'total_amount',
        'payment_method_id': 'payment_method_id',
        'net_amount': 'net_amount',
        'tax_amount': 'tax_amount',
        'currency_id': 'currency_id',
        'exchange_rate': 'exchange_rate',
        'base_currency_net_amount': 'base_currency_net_amount',
        'base_currency_tax_amount': 'base_currency_tax_amount',
        'base_currency_total_amount': 'base_currency_total_amount',
        'base_currency_currency_charge': 'base_currency_currency_charge',
        'reference': 'reference',
        'tax_rate_id': 'tax_rate_id',
        'allocated_artefacts': 'allocated_artefacts',
        'payment_on_account': 'payment_on_account'
    }

    def __init__(self, transaction_type_id=None, contact_id=None, bank_account_id=None, date=None, total_amount=None, payment_method_id=None, net_amount=None, tax_amount=None, currency_id=None, exchange_rate=None, base_currency_net_amount=None, base_currency_tax_amount=None, base_currency_total_amount=None, base_currency_currency_charge=None, reference=None, tax_rate_id=None, allocated_artefacts=None, payment_on_account=None, local_vars_configuration=None):  # noqa: E501
        """PutContactPaymentsContactPayment - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._transaction_type_id = None
        self._contact_id = None
        self._bank_account_id = None
        self._date = None
        self._total_amount = None
        self._payment_method_id = None
        self._net_amount = None
        self._tax_amount = None
        self._currency_id = None
        self._exchange_rate = None
        self._base_currency_net_amount = None
        self._base_currency_tax_amount = None
        self._base_currency_total_amount = None
        self._base_currency_currency_charge = None
        self._reference = None
        self._tax_rate_id = None
        self._allocated_artefacts = None
        self._payment_on_account = None
        self.discriminator = None

        if transaction_type_id is not None:
            self.transaction_type_id = transaction_type_id
        if contact_id is not None:
            self.contact_id = contact_id
        if bank_account_id is not None:
            self.bank_account_id = bank_account_id
        if date is not None:
            self.date = date
        if total_amount is not None:
            self.total_amount = total_amount
        if payment_method_id is not None:
            self.payment_method_id = payment_method_id
        if net_amount is not None:
            self.net_amount = net_amount
        if tax_amount is not None:
            self.tax_amount = tax_amount
        if currency_id is not None:
            self.currency_id = currency_id
        if exchange_rate is not None:
            self.exchange_rate = exchange_rate
        if base_currency_net_amount is not None:
            self.base_currency_net_amount = base_currency_net_amount
        if base_currency_tax_amount is not None:
            self.base_currency_tax_amount = base_currency_tax_amount
        if base_currency_total_amount is not None:
            self.base_currency_total_amount = base_currency_total_amount
        if base_currency_currency_charge is not None:
            self.base_currency_currency_charge = base_currency_currency_charge
        if reference is not None:
            self.reference = reference
        if tax_rate_id is not None:
            self.tax_rate_id = tax_rate_id
        if allocated_artefacts is not None:
            self.allocated_artefacts = allocated_artefacts
        if payment_on_account is not None:
            self.payment_on_account = payment_on_account

    @property
    def transaction_type_id(self):
        """Gets the transaction_type_id of this PutContactPaymentsContactPayment.  # noqa: E501

        The transaction type of the payment  # noqa: E501

        :return: The transaction_type_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: str
        """
        return self._transaction_type_id

    @transaction_type_id.setter
    def transaction_type_id(self, transaction_type_id):
        """Sets the transaction_type_id of this PutContactPaymentsContactPayment.

        The transaction type of the payment  # noqa: E501

        :param transaction_type_id: The transaction_type_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: str
        """

        self._transaction_type_id = transaction_type_id

    @property
    def contact_id(self):
        """Gets the contact_id of this PutContactPaymentsContactPayment.  # noqa: E501

        The contact of the payment  # noqa: E501

        :return: The contact_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: str
        """
        return self._contact_id

    @contact_id.setter
    def contact_id(self, contact_id):
        """Sets the contact_id of this PutContactPaymentsContactPayment.

        The contact of the payment  # noqa: E501

        :param contact_id: The contact_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: str
        """

        self._contact_id = contact_id

    @property
    def bank_account_id(self):
        """Gets the bank_account_id of this PutContactPaymentsContactPayment.  # noqa: E501

        The bank account of the payment  # noqa: E501

        :return: The bank_account_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: str
        """
        return self._bank_account_id

    @bank_account_id.setter
    def bank_account_id(self, bank_account_id):
        """Sets the bank_account_id of this PutContactPaymentsContactPayment.

        The bank account of the payment  # noqa: E501

        :param bank_account_id: The bank_account_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: str
        """

        self._bank_account_id = bank_account_id

    @property
    def date(self):
        """Gets the date of this PutContactPaymentsContactPayment.  # noqa: E501

        The date the payment was made  # noqa: E501

        :return: The date of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: date
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this PutContactPaymentsContactPayment.

        The date the payment was made  # noqa: E501

        :param date: The date of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: date
        """

        self._date = date

    @property
    def total_amount(self):
        """Gets the total_amount of this PutContactPaymentsContactPayment.  # noqa: E501

        The total amount of the payment  # noqa: E501

        :return: The total_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount):
        """Sets the total_amount of this PutContactPaymentsContactPayment.

        The total amount of the payment  # noqa: E501

        :param total_amount: The total_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._total_amount = total_amount

    @property
    def payment_method_id(self):
        """Gets the payment_method_id of this PutContactPaymentsContactPayment.  # noqa: E501

        The ID of the Payment Method.  # noqa: E501

        :return: The payment_method_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: str
        """
        return self._payment_method_id

    @payment_method_id.setter
    def payment_method_id(self, payment_method_id):
        """Sets the payment_method_id of this PutContactPaymentsContactPayment.

        The ID of the Payment Method.  # noqa: E501

        :param payment_method_id: The payment_method_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: str
        """

        self._payment_method_id = payment_method_id

    @property
    def net_amount(self):
        """Gets the net_amount of this PutContactPaymentsContactPayment.  # noqa: E501

        The net amount of the payment  # noqa: E501

        :return: The net_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._net_amount

    @net_amount.setter
    def net_amount(self, net_amount):
        """Sets the net_amount of this PutContactPaymentsContactPayment.

        The net amount of the payment  # noqa: E501

        :param net_amount: The net_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._net_amount = net_amount

    @property
    def tax_amount(self):
        """Gets the tax_amount of this PutContactPaymentsContactPayment.  # noqa: E501

        The tax amount of the payment  # noqa: E501

        :return: The tax_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._tax_amount

    @tax_amount.setter
    def tax_amount(self, tax_amount):
        """Sets the tax_amount of this PutContactPaymentsContactPayment.

        The tax amount of the payment  # noqa: E501

        :param tax_amount: The tax_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._tax_amount = tax_amount

    @property
    def currency_id(self):
        """Gets the currency_id of this PutContactPaymentsContactPayment.  # noqa: E501

        The ID of the Currency.  # noqa: E501

        :return: The currency_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: str
        """
        return self._currency_id

    @currency_id.setter
    def currency_id(self, currency_id):
        """Sets the currency_id of this PutContactPaymentsContactPayment.

        The ID of the Currency.  # noqa: E501

        :param currency_id: The currency_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: str
        """

        self._currency_id = currency_id

    @property
    def exchange_rate(self):
        """Gets the exchange_rate of this PutContactPaymentsContactPayment.  # noqa: E501

        The exchange rate of the payment  # noqa: E501

        :return: The exchange_rate of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._exchange_rate

    @exchange_rate.setter
    def exchange_rate(self, exchange_rate):
        """Sets the exchange_rate of this PutContactPaymentsContactPayment.

        The exchange rate of the payment  # noqa: E501

        :param exchange_rate: The exchange_rate of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._exchange_rate = exchange_rate

    @property
    def base_currency_net_amount(self):
        """Gets the base_currency_net_amount of this PutContactPaymentsContactPayment.  # noqa: E501

        The net amount of the payment in base currency  # noqa: E501

        :return: The base_currency_net_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._base_currency_net_amount

    @base_currency_net_amount.setter
    def base_currency_net_amount(self, base_currency_net_amount):
        """Sets the base_currency_net_amount of this PutContactPaymentsContactPayment.

        The net amount of the payment in base currency  # noqa: E501

        :param base_currency_net_amount: The base_currency_net_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._base_currency_net_amount = base_currency_net_amount

    @property
    def base_currency_tax_amount(self):
        """Gets the base_currency_tax_amount of this PutContactPaymentsContactPayment.  # noqa: E501

        The tax amount of the payment in base currency  # noqa: E501

        :return: The base_currency_tax_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._base_currency_tax_amount

    @base_currency_tax_amount.setter
    def base_currency_tax_amount(self, base_currency_tax_amount):
        """Sets the base_currency_tax_amount of this PutContactPaymentsContactPayment.

        The tax amount of the payment in base currency  # noqa: E501

        :param base_currency_tax_amount: The base_currency_tax_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._base_currency_tax_amount = base_currency_tax_amount

    @property
    def base_currency_total_amount(self):
        """Gets the base_currency_total_amount of this PutContactPaymentsContactPayment.  # noqa: E501

        The total amount of the payment in base currency  # noqa: E501

        :return: The base_currency_total_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._base_currency_total_amount

    @base_currency_total_amount.setter
    def base_currency_total_amount(self, base_currency_total_amount):
        """Sets the base_currency_total_amount of this PutContactPaymentsContactPayment.

        The total amount of the payment in base currency  # noqa: E501

        :param base_currency_total_amount: The base_currency_total_amount of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._base_currency_total_amount = base_currency_total_amount

    @property
    def base_currency_currency_charge(self):
        """Gets the base_currency_currency_charge of this PutContactPaymentsContactPayment.  # noqa: E501

        The currency conversion charges in base currency  # noqa: E501

        :return: The base_currency_currency_charge of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: float
        """
        return self._base_currency_currency_charge

    @base_currency_currency_charge.setter
    def base_currency_currency_charge(self, base_currency_currency_charge):
        """Sets the base_currency_currency_charge of this PutContactPaymentsContactPayment.

        The currency conversion charges in base currency  # noqa: E501

        :param base_currency_currency_charge: The base_currency_currency_charge of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: float
        """

        self._base_currency_currency_charge = base_currency_currency_charge

    @property
    def reference(self):
        """Gets the reference of this PutContactPaymentsContactPayment.  # noqa: E501

        A reference for the payment  # noqa: E501

        :return: The reference of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this PutContactPaymentsContactPayment.

        A reference for the payment  # noqa: E501

        :param reference: The reference of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: str
        """

        self._reference = reference

    @property
    def tax_rate_id(self):
        """Gets the tax_rate_id of this PutContactPaymentsContactPayment.  # noqa: E501

        The ID of the Tax Rate.  # noqa: E501

        :return: The tax_rate_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: str
        """
        return self._tax_rate_id

    @tax_rate_id.setter
    def tax_rate_id(self, tax_rate_id):
        """Sets the tax_rate_id of this PutContactPaymentsContactPayment.

        The ID of the Tax Rate.  # noqa: E501

        :param tax_rate_id: The tax_rate_id of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: str
        """

        self._tax_rate_id = tax_rate_id

    @property
    def allocated_artefacts(self):
        """Gets the allocated_artefacts of this PutContactPaymentsContactPayment.  # noqa: E501


        :return: The allocated_artefacts of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: list[PostContactPaymentsContactPaymentAllocatedArtefacts]
        """
        return self._allocated_artefacts

    @allocated_artefacts.setter
    def allocated_artefacts(self, allocated_artefacts):
        """Sets the allocated_artefacts of this PutContactPaymentsContactPayment.


        :param allocated_artefacts: The allocated_artefacts of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: list[PostContactPaymentsContactPaymentAllocatedArtefacts]
        """

        self._allocated_artefacts = allocated_artefacts

    @property
    def payment_on_account(self):
        """Gets the payment_on_account of this PutContactPaymentsContactPayment.  # noqa: E501


        :return: The payment_on_account of this PutContactPaymentsContactPayment.  # noqa: E501
        :rtype: PostContactPaymentsContactPaymentPaymentOnAccount
        """
        return self._payment_on_account

    @payment_on_account.setter
    def payment_on_account(self, payment_on_account):
        """Sets the payment_on_account of this PutContactPaymentsContactPayment.


        :param payment_on_account: The payment_on_account of this PutContactPaymentsContactPayment.  # noqa: E501
        :type: PostContactPaymentsContactPaymentPaymentOnAccount
        """

        self._payment_on_account = payment_on_account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutContactPaymentsContactPayment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PutContactPaymentsContactPayment):
            return True

        return self.to_dict() != other.to_dict()
