# coding: utf-8

"""
    Sage Accounting API - User Accounts

    Documentation of the Sage Business Cloud Accounting API.  # noqa: E501

    The version of the OpenAPI document: 3.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sage.configuration import Configuration


class PutBusinessesBusiness(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'address_line_1': 'str',
        'address_line_2': 'str',
        'city': 'str',
        'region': 'str',
        'postal_code': 'str',
        'telephone': 'str',
        'mobile': 'str',
        'website': 'str'
    }

    attribute_map = {
        'name': 'name',
        'address_line_1': 'address_line_1',
        'address_line_2': 'address_line_2',
        'city': 'city',
        'region': 'region',
        'postal_code': 'postal_code',
        'telephone': 'telephone',
        'mobile': 'mobile',
        'website': 'website'
    }

    def __init__(self, name=None, address_line_1=None, address_line_2=None, city=None, region=None, postal_code=None, telephone=None, mobile=None, website=None, local_vars_configuration=None):  # noqa: E501
        """PutBusinessesBusiness - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._address_line_1 = None
        self._address_line_2 = None
        self._city = None
        self._region = None
        self._postal_code = None
        self._telephone = None
        self._mobile = None
        self._website = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if address_line_1 is not None:
            self.address_line_1 = address_line_1
        if address_line_2 is not None:
            self.address_line_2 = address_line_2
        if city is not None:
            self.city = city
        if region is not None:
            self.region = region
        if postal_code is not None:
            self.postal_code = postal_code
        if telephone is not None:
            self.telephone = telephone
        if mobile is not None:
            self.mobile = mobile
        if website is not None:
            self.website = website

    @property
    def name(self):
        """Gets the name of this PutBusinessesBusiness.  # noqa: E501

        The name of the business  # noqa: E501

        :return: The name of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PutBusinessesBusiness.

        The name of the business  # noqa: E501

        :param name: The name of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def address_line_1(self):
        """Gets the address_line_1 of this PutBusinessesBusiness.  # noqa: E501

        The first line of the business address  # noqa: E501

        :return: The address_line_1 of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._address_line_1

    @address_line_1.setter
    def address_line_1(self, address_line_1):
        """Sets the address_line_1 of this PutBusinessesBusiness.

        The first line of the business address  # noqa: E501

        :param address_line_1: The address_line_1 of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._address_line_1 = address_line_1

    @property
    def address_line_2(self):
        """Gets the address_line_2 of this PutBusinessesBusiness.  # noqa: E501

        The second line of the business address  # noqa: E501

        :return: The address_line_2 of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._address_line_2

    @address_line_2.setter
    def address_line_2(self, address_line_2):
        """Sets the address_line_2 of this PutBusinessesBusiness.

        The second line of the business address  # noqa: E501

        :param address_line_2: The address_line_2 of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._address_line_2 = address_line_2

    @property
    def city(self):
        """Gets the city of this PutBusinessesBusiness.  # noqa: E501

        The business address town/city  # noqa: E501

        :return: The city of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this PutBusinessesBusiness.

        The business address town/city  # noqa: E501

        :param city: The city of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def region(self):
        """Gets the region of this PutBusinessesBusiness.  # noqa: E501

        The business address state/province/region  # noqa: E501

        :return: The region of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this PutBusinessesBusiness.

        The business address state/province/region  # noqa: E501

        :param region: The region of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._region = region

    @property
    def postal_code(self):
        """Gets the postal_code of this PutBusinessesBusiness.  # noqa: E501

        The business address postal code/zipcode  # noqa: E501

        :return: The postal_code of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this PutBusinessesBusiness.

        The business address postal code/zipcode  # noqa: E501

        :param postal_code: The postal_code of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._postal_code = postal_code

    @property
    def telephone(self):
        """Gets the telephone of this PutBusinessesBusiness.  # noqa: E501

        The telephone of the business  # noqa: E501

        :return: The telephone of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._telephone

    @telephone.setter
    def telephone(self, telephone):
        """Sets the telephone of this PutBusinessesBusiness.

        The telephone of the business  # noqa: E501

        :param telephone: The telephone of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._telephone = telephone

    @property
    def mobile(self):
        """Gets the mobile of this PutBusinessesBusiness.  # noqa: E501

        The mobile of the business  # noqa: E501

        :return: The mobile of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._mobile

    @mobile.setter
    def mobile(self, mobile):
        """Sets the mobile of this PutBusinessesBusiness.

        The mobile of the business  # noqa: E501

        :param mobile: The mobile of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._mobile = mobile

    @property
    def website(self):
        """Gets the website of this PutBusinessesBusiness.  # noqa: E501

        The website of the business  # noqa: E501

        :return: The website of this PutBusinessesBusiness.  # noqa: E501
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website):
        """Sets the website of this PutBusinessesBusiness.

        The website of the business  # noqa: E501

        :param website: The website of this PutBusinessesBusiness.  # noqa: E501
        :type: str
        """

        self._website = website

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutBusinessesBusiness):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PutBusinessesBusiness):
            return True

        return self.to_dict() != other.to_dict()
